{
 "title": "Fitbit",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Resting heart rate BPM",
   "type": "timeseries",
   "description": "Resting heart rate. Beats per minute",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"heartrate\" and\n    r.type == \"resting\" and\n    r._field == \"rate\"\n  )\n  |> aggregateWindow(every: 24h, fn: last, createEmpty: false)\n\n\n\n\n  \n  "
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "timeseries",
   "description": "Heart Rate Intraday Time Series",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> filter(fn: (r) =>\n    r._measurement == \"heartrate\" and\n    r.type == \"heart\" and\n    r._field == \"rate\"\n  )\n"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "barchart",
   "description": "Steps activity time series",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\" and r[\"activity\"] == \"steps\")\n  |> aggregateWindow(every: 1h, fn: sum)"
    }
   ]
  },
  {
   "title": "Total steps",
   "type": "gauge",
   "description": "Total steps",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"activities\" and\n    r.activity == \"steps\" and\n    r._field == \"steps\"\n  )\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> yield(name: \"steps/h\")"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"distance\" and r[\"activity\"] == \"distance\")\n  |> map(fn: (r) => ({r with _value: r._value * 1000.0}))\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> yield(name: \"distance\")\n"
    }
   ]
  },
  {
   "title": "Total distance",
   "type": "gauge",
   "description": "Distance activity. Total",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"activities\" and\n    r.activity == \"distance\" and\n    r._field == \"distance\"\n  )\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> yield(name: \"meters\")\n  \n"
    }
   ]
  },
  {
   "title": "Floors",
   "type": "barchart",
   "description": "Activities Floors",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"floors\" and r[\"activity\"] == \"floors\")\n  |> aggregateWindow(every: 1h, fn: sum)"
    }
   ]
  },
  {
   "title": "Total floors",
   "type": "gauge",
   "description": "Total floors Activities",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fitbit\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"activities\" and\n    r.activity == \"floors\" and\n    r._field == \"floors\"\n  )\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> yield(name: \"floors_total\")"
    }
   ]
  }
 ]
}